// src/pages/api/games.js
export default function handler(req, res) {
  const games = [
    {
      id: 1,
      name: "The Legend of Zelda: Breath of the Wild",
      genre: "Action-Adventure",
      difficulty: "Medium",
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 2,
      name: "God of War",
      genre: "Action",
      difficulty: "Hard",
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 3,
      name: "The Witcher 3: Wild Hunt",
      genre: "RPG",
      difficulty: "Hard",
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 4,
      name: "Dark Souls III",
      genre: "Action RPG",
      difficulty: "Very Hard",
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 5,
      name: "Overwatch",
      genre: "First-Person Shooter",
      difficulty: "Medium",
      storyDriven: false,
      multiplayer: true,
    },
    {
      id: 6,
      name: "Minecraft",
      genre: "Sandbox",
      difficulty: "Easy",
      storyDriven: false,
      multiplayer: true,
    },
    {
      id: 7,
      name: "Among Us",
      genre: "Party",
      difficulty: "Easy",
      storyDriven: false,
      multiplayer: true,
    },
    {
      id: 8,
      name: "Final Fantasy VII Remake",
      genre: "RPG",
      difficulty: "Medium",
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 9,
      name: "Stardew Valley",
      genre: "Simulation",
      difficulty: "Easy",
      storyDriven: false,
      multiplayer: true,
    },
    {
      id: 10,
      name: "Resident Evil Village",
      genre: "Survival Horror",
      difficulty: "Medium",
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 11,
      name: "Hades",
      genre: "Rogue-like",
      difficulty: "Medium",
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 12,
      name: "Sekiro: Shadows Die Twice",
      genre: "Action-Adventure",
      difficulty: "Very Hard",
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 13,
      name: "Call of Duty: Warzone",
      genre: "Battle Royale",
      difficulty: "Medium",
      storyDriven: false,
      multiplayer: true,
    },
    {
      id: 14,
      name: "Fortnite",
      genre: "Battle Royale",
      difficulty: "Medium",
      storyDriven: false,
      multiplayer: true,
    },
    {
      id: 15,
      name: "Animal Crossing: New Horizons",
      genre: "Simulation",
      difficulty: "Easy",
      storyDriven: false,
      multiplayer: true,
    },
    {
      id: 16,
      name: "Ghost of Tsushima",
      genre: "Action-Adventure",
      difficulty: "Medium",
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 17,
      name: "Doom Eternal",
      genre: "First-Person Shooter",
      difficulty: "Hard",
      storyDriven: false,
      multiplayer: false,
    },
    {
      id: 18,
      name: "Cyberpunk 2077",
      genre: "RPG",
      difficulty: "Medium",
      desc: "Star Wars Outlaws is an open world video game developed by Massive Entertainment and published by Ubisoft in collaboration with Lucasfilm Games. The game is story-driven, features an open world, and utilizes Massive Entertainment's proprietary Snowdrop game engine.",
      // featured: true,
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 19,
      name: "Genshin Impact",
      genre: "Action RPG",
      difficulty: "Medium",
      storyDriven: true,
      multiplayer: true,
    },
    {
      id: 20,
      name: "The Last of Us Part II",
      genre: "Action-Adventure",
      difficulty: "Hard",
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 21,
      name: "WarHammer 40k: Space Marine 2",
      genre: "Action-Adventure",
      desc: "Warhammer 40,000: Space Marine 2 on Steam. Embody the superhuman skill and brutality of a Space Marine. Unleash deadly abilities and devastating weaponry to obliterate the relentless Tyranid swarms. Defend the Imperium in spectacular third-person action in solo or multiplayer modes.",
      difficulty: "Medium",
      storyDriven: true,
      multiplayer: false,
      featured: true,
      thumbnail: "/images/games/warhammer-space-marine/thumbnail.webp",
      disc: "/images/games/warhammer-space-marine/disc.webp",
      logo: "/images/games/warhammer-space-marine/logo.webp",
      additionalImages: [
        "/images/games/warhammer-space-marine/additional/image1.webp",
      ],
    },
    {
      id: 22,
      name: "Black Myth: Wu Kong",
      genre: "Action-Adventure",
      desc: "Black Myth: Wukong is an action role-playing game. It has elements characteristic to the Soulslike subgenre. The game is played in single-player mode from a third-person perspective. The player controls a monkey protagonist referred to as the Destined One, who is based on Sun Wukong from the Journey to the West.",
      difficulty: "Hard",
      // featured: true,
      storyDriven: true,
      multiplayer: false,
    },
    {
      id: 23,
      name: "Marvel's Spider-Man 2",
      genre: "Action-Adventure",
      difficulty: "Hard",
      // featured: true,
      storyDriven: true,
      multiplayer: false,
    },
  ];

  // Send the games data as a response
  res.status(200).json(games);
}
